# Generated by Django 2.1.7 on 2019-03-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes2',
            field=models.TimeField(default=1, help_text='Final time', verbose_name='Final time'),
            preserve_default=False,
        ),
    ]
