# Generated by Django 2.1.7 on 2019-03-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_notes2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Schedules', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='notes2',
        ),
    ]
