# Generated by Django 2.1.7 on 2019-03-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.IntegerField(choices=[(1, 'Danillo Vieira'), (2, 'Sun park'), (3, 'Demetrious Robinson')], default=(1, 'Danillo Vieira')),
        ),
    ]
