# Generated by Django 2.1.5 on 2019-03-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tattoo',
            name='appointment',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jointable',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Appointment'),
        ),
        migrations.AddField(
            model_name='jointable',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Artist'),
        ),
        migrations.AddField(
            model_name='jointable',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile'),
        ),
        migrations.AddField(
            model_name='jointable',
            name='tattoo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Tattoo'),
        ),
    ]
