# Generated by Django 2.1.5 on 2019-03-18 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='tattoo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Tattoo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tattoo',
            name='available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
