# Generated by Django 2.1.5 on 2019-03-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190318_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
