# Generated by Django 2.1.5 on 2019-03-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190319_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='address',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.TextField(default='Venice', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.TextField(default='CA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Artist'),
        ),
    ]
