# Generated by Django 2.1.7 on 2019-03-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoo',
            name='url',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='tattoo',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
