# Generated by Django 2.1.5 on 2019-03-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190318_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='tattoo',
        ),
    ]
