# Generated by Django 2.1.7 on 2019-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190320_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoo',
            name='url',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
