# Generated by Django 2.1.7 on 2019-03-20 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190320_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artist',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='main_app.Artist'),
            preserve_default=False,
        ),
    ]
