# Generated by Django 2.1.7 on 2019-03-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190320_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tattoo',
            name='url',
        ),
        migrations.AddField(
            model_name='event',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tattoo',
            name='available',
            field=models.BooleanField(),
        ),
    ]
