# Generated by Django 2.1.7 on 2019-03-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190320_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artist',
        ),
    ]
